### ISSUE TITLE
User Experience - Search Page - Open results in another tab AND save the last date input when going back from the record to the search page

### ISSUE THREAD

**Issue by dolivetoa** [aws-samples/amazon-transcribe-post-call-analytics#130]
As  user when I do a search for a specific date, and get many results...If I need to check one and going back the date is not saved...which if I am going back years I will need awfully set the date again.
Also if I would like to avoid that and open the result in another tab I cannot do that.

**Comment by rstrahan** [comment]
UI has changed a lot since this issue.. Can you reopen if it's still a problem with the latest version. Tx!
