### ISSUE TITLE
System defining talkers randomly

### ISSUE THREAD

**Issue by mohammedshawa97** [aws-samples/amazon-transcribe-post-call-analytics#152]
Hello,

The system start defining the talkers right then it defining randomly when the talker stop talking for seconds (define customer is talking while agent was talking , and defining agent is talking while actually customer was talking) which will lead into inaccurate evaluation of the voice.

There is another issue that we have Arabic language calls so the the system can’t translate the English words sometimes and will just skip what the customer said, can we add 2 languages?

Regards,

**Comment by rstrahan** [comment]
Hi @mohammedshawa97   Are you still having an issue.. If so can you please clarify more exactly what you mean - I 'm sorry, but I cannot understand.  Attaching screenshots might help to illustrate clearly what issue you are facing.  Please test with the most recent PCA version.

For now, closing the issue.. Please reopen if you still have the problem and need help.
