### ISSUE TITLE
Make UI stack conditional

### ISSUE THREAD

**Issue by bharvillsos** [aws-samples/amazon-transcribe-post-call-analytics#153]
Like the Kendra portion of the stack, the UI could be made optional as well. This would allow consumers that don't want a website and/or don't want to manage a Cognito stack to be able to skip those.

**Comment by claudinha587** [comment]
I agree, I would also like to have the UI as an option. Right now UI stack is failing (can't build the stack) so I can't build the rest of the solution either. If it was an option at least I could test the rest.

**Comment by rstrahan** [comment]
It's a good idea. But it's not a priority request right now.  We'd happily consider accepting a pull request though, if you want to implement a backward compatible method for optionally choosing not to deploy the UI.. 
Closing as not planned for now.
Thanks!
