### ISSUE TITLE
Cloudformation stack failing due to recent S3 bucket changes on ACLs

### ISSUE THREAD

**Issue by ben-founded** [aws-samples/amazon-transcribe-post-call-analytics#163]
Hi,

The stack fails to deploy in either of the supported regions.  Info from the failed stack is:

`The following resource(s) failed to create: [LogBucket].`

`Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership;`

I believe it's due to this recent change to S3 default settings made last month (April 2023)

_Amazon S3 will automatically enable S3 Block Public Access and disable access control lists for all new buckets starting in April 2023_
https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

It looks like the stacks need some changes to be made following the defaults S3 ACL settings.

Thanks

**Comment by ben-founded** [comment]
Thanks for the quick change @aarondiuz

**Comment by claudinha587** [comment]
I am having a similar error I think
![image](https://user-images.githubusercontent.com/16297015/236698326-614b8030-8cc3-46ae-8cf2-b0888f4f9ad5.png)

Web stack inside PCAUI fails making the complete stack failing https://github.com/aws-samples/amazon-transcribe-post-call-analytics/issues/165

**Comment by rstrahan** [comment]
resolved
