### ISSUE TITLE
custom vocabulary not work!

### ISSUE THREAD

**Issue by muntherqasaimeh** [aws-samples/amazon-transcribe-post-call-analytics#170]
Hello
I tried to update my cloud formation PCA stack, to add a custom vocabulary txt file.
I added the file on custom vocabulary inside the AWS transcribe list and I added the file name inside the stack and its updated correctly.
but I found that no improvement in text extraction, I uploaded the call record again and the same low performance
why the custom vocabulary didnt improve the text extraction performance? and how can I improve text extraction performance?

Note : 
the call records languages is Arabic

**Comment by rstrahan** [comment]
Assuming related to #171 - closing
