### ISSUE TITLE
Custom vocabulary not added correctly

### ISSUE THREAD

**Issue by muntherqasaimeh** [aws-samples/amazon-transcribe-post-call-analytics#171]
Hi 
I tried to add a custom vocabulary to AWS transcribe
after that I added the custom vocabulary name inside the stack and I updated my stack 
then I tried to add a new call to process it
I found that no improvement in text extraction 
on the another hand, I found that the custom voc not added yet!!!
you can find screenshot that the custom voc not added while I added it to my stack 
how can I solve this???
![image](https://github.com/aws-samples/amazon-transcribe-post-call-analytics/assets/80498650/45b467fd-c871-402c-8f77-35019d8886be)
![image](https://github.com/aws-samples/amazon-transcribe-post-call-analytics/assets/80498650/e472bd4c-b16b-414e-a89d-271d1968dadb)

**Comment by rstrahan** [comment]
Hi @muntherqasaimeh, To help troubleshoot, can you:
1. attach screenshot of the custom vocabulary listed in the Amazon Transcribe console.. including the Language setting for the vocab
2. attach screenshot of the current parameter values for your stack (in Cloudformation, select 'Parameters' tab) - showing the value for `VocabularyName` (at the end of the list).. Want to make sure it exactly matches
3. Check the value of the 'VocabularyName' parameter in System Manager Parameter Store ([link](https://us-east-1.console.aws.amazon.com/systems-manager/parameters/VocabularyName/description?region=us-east-1&tab=Table)].. include screenshot of that too
4. If everything aligns perfectly so far, then check the CloudWatch logs for the `SFStartTranscribeJob` Lambda function and share the logs reported there.. it should identify the custom vocabukary used for the job, based on the settings..

**Comment by rstrahan** [comment]
Assuming resolved since no follow-up. Please reopen if the issue remains. Tx.

**Comment by muntherqasaimeh** [comment]
Hello

I noticed a new issue
when I tried to update my stack I just removed the custom voc from the cloudformation to make it empty


so the stack is not able to be updated, giving errors custom vocabulary name parameter

I need to let it empty I dont want custom voc

**Comment by T2MWorks-Mitch** [comment]
if the Name of the dictionary has to have the language suffix , why does the template tell you to leave it off ? 
once I added my language suffix to the filename it was applied properly 

for anyone coming here with the same issue - this is what worked for me 

- cloudfommation dictionary entry: myfile
- dictionary file name: myfile-en-us ( or whatever langauge suffix )
