### ISSUE TITLE
Supporting Arabic Language

### ISSUE THREAD

**Issue by muntherqasaimeh** [aws-samples/amazon-transcribe-post-call-analytics#172]
Hello
I noticed that the some analytics features and options only available for English not supported other languages.
such as Call Analytics Summary, Loudness/Sentiment.
you can find screenshots attached 
![image](https://github.com/aws-samples/amazon-transcribe-post-call-analytics/assets/80498650/2aa976eb-2f94-4848-a46a-cfe98420e0a2)
![image](https://github.com/aws-samples/amazon-transcribe-post-call-analytics/assets/80498650/661e881d-7b2f-4053-b440-0503d3018ce2)

while empty results in Arabic 
![image](https://github.com/aws-samples/amazon-transcribe-post-call-analytics/assets/80498650/d860f8e8-8d93-4352-8290-d4f0385ae32b)

**Comment by rstrahan** [comment]
Yes, please see https://docs.aws.amazon.com/transcribe/latest/dg/supported-languages.html for supported languages / features matrix. Thanks.
