### ISSUE TITLE
Generative AI summarization not show up

### ISSUE THREAD

**Issue by fbanespo1** [aws-samples/amazon-transcribe-post-call-analytics#177]
I have enabled the CallSummarization with Sagemaker but I get "GenAI Transcript Summary
No Summary Available" with all the example calls. Any help?
Thanks
Tony

**Comment by rstrahan** [comment]
Hi @fbanespo1 - Can you confirm which region you have deployed in? us-east-1? 
I'll see if I can repro.

**Comment by rstrahan** [comment]
Update.. Installed in us-east-1 with SAGEMAKER summarization specified.. Cannot reproduce the problem.. See screenshots of summary from sample call.

![image](https://github.com/aws-samples/amazon-transcribe-post-call-analytics/assets/10953374/f2cb3647-d330-492d-aa07-9fc48186ec34)

So we need to dig into what's different in your stack.  Some questions:
1. Confirm if you built and published PCA from the repo, or if you deployed from published template?
  - if you built PCA from the repo, please confirm the region
2. Confirm if you deployed a new stack, or updated an existing one to enable summarization?
  - NOT If you updated an existing stack, the sample files are not automatically reprocessed.. changes are effective for only new files.. To force reprocessing, you can use the S3 console to select and copy the sample files from the InputBucket audioInput folder back into the same location to re-trigger the workflow. 

Please also check the logs generated by `SFSummarize` Lambda function - to see if there are any failures logged..

**Comment by fbanespo1** [comment]
Thank you for that please find below my comments on that

> Update.. Installed in us-east-1 with SAGEMAKER summarization specified.. Cannot reproduce the problem.. See screenshots of summary from sample call.
> 
> ![image](https://user-images.githubusercontent.com/10953374/255657189-f2cb3647-d330-492d-aa07-9fc48186ec34.png)
> 
> So we need to dig into what's different in your stack. Some questions:
> 
> 1. Confirm if you built and published PCA from the repo, or if you deployed from published template?
-- I confirm that I used the stack from the blog in us-east-1
> * if you built PCA from the repo, please confirm the region
> 
> 2. Confirm if you deployed a new stack, or updated an existing one to enable summarization?
Deployed a new stack
> * NOT If you updated an existing stack, the sample files are not automatically reprocessed.. changes are effective for only new files.. To force reprocessing, you can use the S3 console to select and copy the sample files from the InputBucket audioInput folder back into the same location to re-trigger the workflow.
> 
> Please also check the logs generated by `SFSummarize` Lambda function - to see if there are any failures logged..

Thanks
Tony

**Comment by rstrahan** [comment]
OK, thanks for reply.  To troubleshoot further, Please also check the logs generated by SFSummarize Lambda function - to see if there are any failures logged.. Let me know if you need guidance on how to do that. Tx.

**Comment by fbanespo1** [comment]
> OK, thanks for reply. To troubleshoot further, Please also check the logs generated by SFSummarize Lambda function - to see if there are any failures logged.. Let me know if you need guidance on how to do that. Tx.

Sorry forgot to mention - No issues were found in the log. Meanwhile, I am deploying another stack and see how it goes and keep you posted.

Thanks
Tony

**Comment by fbanespo1** [comment]
Update: After stack redeployment, it works as expected, I guess something was missed in the previous stack from my hand. Thanks a lot for your help and support.

Tony

**Comment by fbanespo1** [comment]
Update: After stack redeployment, it works as expected, I guess something was missed in the previous stack from my hand. Thanks a lot for your help and support.

Tony

**Comment by rstrahan** [comment]
Great, glad to hear it, and thanks for confirming.

Sent from Workspace ONE Boxer

On Jul 24, 2023 4:17 PM, fbanespo1 ***@***.***> wrote:

Update: After stack redeployment, it works as expected, I guess something was missed in the previous stack from my hand. Thanks a lot for your help and support.

Tony
