### ISSUE TITLE
PCA deployment failing with FFmpeg stack

### ISSUE THREAD

**Issue by chrislott** [aws-samples/amazon-transcribe-post-call-analytics#181]
Hi all - we've identified an issue where FFmpeg does not properly download static binaries with the default parameter's url.

The workaround is to change the value of the `ffmpegDownloadUrl` parameter to be http, instead of https, for example: `http://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.4-amd64-static.tar.xz`

This issue will be resolved in the next release of PCA.

**Comment by rstrahan** [comment]
Resolved by changing default value for `ffmpegDownloadUrl` in v0.7.0
