### ISSUE TITLE
LLM Key Requirement Results in Stack Creation Failure

### ISSUE THREAD

**Issue by mmarthab** [aws-samples/amazon-transcribe-post-call-analytics#183]
Previously the solution deployment was getting deployed successfully, since user was using "SAGEMAKER for call summarization and opting not to provide an LLM key.

But now the same deployment fails because it requires the LLM key even with sagemaker option selected.

I checked the 2 templates the previous working one and the failing one and noted on failing template there is a secret manager secret resource that requires the LLM key hence why it fails. 

But the previous working template has no such resource. Is there a way some changes were made here?

**Comment by mmarthab** [comment]
Using the below version of the template:
Amazon Transcribe Post Call Analytics - PCA (v0.7.0) (uksb-1sn29lk73)

**Comment by rstrahan** [comment]
Thanks @mmarthab - Fixed in v0.7.1 by changing the default value of the LLM APi Key parameter so it will no longer default to an empty string.  Please confirm it works as expected.  Tx.
