### ISSUE TITLE
Clarification on 3rd party telephony systems (Genesys)

### ISSUE THREAD

**Issue by not-sure-about-this** [aws-samples/amazon-transcribe-post-call-analytics#186]
In the [Integration with Telephony CTR Files](https://github.com/aws-samples/amazon-transcribe-post-call-analytics#integration-with-telephony-ctr-files) section it states that it has support for Genesys, is this [Genesys Cloud](https://www.genesys.com/)?

If yes I have the following questions

- The section doesn't really provide a lot of information on how to integrate Genesys with this application. From what I understand the following files should be inserted into the S3 originalAudio folder, an audio file, a _metadata.json and _call_metadata.json all using the same conversation ID e.g. (76ed3310-1baa-4fb5-8b4f-27a485e21f7f.wav, 76ed3310-1baa-4fb5-8b4f-27a485e21f7f.wav_metadata.json, 76ed3310-1baa-4fb5-8b4f-27a485e21f7f.wav_call_metadata.json). But it is never explain how those files are meant to be generated, I would assume for large scale exporting something like https://help.mypurecloud.com/articles/about-the-aws-s3-recording-bulk-actions-integration/ would be used, but the _call_metadata.json is not a part of this, are meant to use the Genesys conservation API for this?
![image](https://github.com/aws-samples/amazon-transcribe-post-call-analytics/assets/147459771/e0252123-45f8-4f0f-afd4-5c7b148c08a2) 

- In the image above you might have noticed that this call in Genesys has multiple recordings for one interaction, how should this be handled?
-  In external conference calls (where one of the agent/Participan is not a part of the Genesys system), will the identification of agents, customers, ivr, acd still work correctly?

**Comment by rstrahan** [comment]
@drandrewkane - this one is for you :)

**Comment by chrislott** [comment]
Hi not-sure-about-this,

Yes, this is for Genesys Cloud. You will need to utilize their APIs, notably [/api/v2/analytics/conversations/details/query/](https://developer.genesys.cloud/devapps/api-explorer#post-api-v2-analytics-conversations-details-query) for the metadata.json and [/api/v2/conversations/{conversation_id}/recordingmetadata/](https://developer.genesys.cloud/devapps/api-explorer#get-api-v2-conversations--conversationId--recordingmetadata) for the call_metadata.json file. 

The first step is to get the conversationid for the calls you want to analyze, using [/api/v2/analytics/conversations/details/query/](https://developer.genesys.cloud/devapps/api-explorer#post-api-v2-analytics-conversations-details-query). This api has a date interval and paging so you can retrieve the calls that you need. For each conversation in the output, save that as (file)_metadata.json -- for example 123456.wav_metadata.json.

For each of the conversations you retrieve from the query, you can then loop through them with the [/api/v2/conversations/{conversation_id}/recordingmetadata/](https://developer.genesys.cloud/devapps/api-explorer#get-api-v2-conversations--conversationId--recordingmetadata) to generate the _call_metadata.json. Write this to (file)_call_metadata.json, for example, 123456.wav_call_metadata.json.

We'll work on adding more documentation on this in an upcoming release.

Chris

**Comment by realtek8723** [comment]
Hi Chris,

      I also got same questions. I have tried the API  [/api/v2/conversations/{conversation_id}/recordingmetadata/](https://developer.genesys.cloud/devapps/api-explorer#get-api-v2-conversations--conversationId--recordingmetadata) to get (file)_call_metadata.json, And uploaded same to s3 bucket along with wav, wav_metadata.json files but itseems this recording not even showing in pca dashboard call list, It got failed in the middle of the process.
       
      In addition to this, how do we differentiate IVR, agent and customer voices for analysys. And i checked the JSON which we got from the above API i couldn't find any relevent information which differentiate between Agent, IVR voices.

Thanks in advance

**Comment by chrislott** [comment]
Hi realtek8723, 

What step function did it fail at, and do you have the Lambda logs?

Chris

**Comment by rstrahan** [comment]
Closed due to lack of follow-up. Please reopen if issue remains.
