### ISSUE TITLE
transcription search web UI opens with an error page after deployment

### ISSUE THREAD

**Issue by ganapras** [aws-samples/amazon-transcribe-post-call-analytics#190]
After deploying the latest version of Post call Analytics solution, launching the transcription search web UI link brings up an error welcome page.  Please see attached screenshot for details

![Screenshot 2023-10-11 at 9 22 19 AM](https://github.com/aws-samples/amazon-transcribe-post-call-analytics/assets/75448444/9b1ce1f4-4883-4c88-86cd-f156c092e920)

**Comment by ganapras** [comment]
Found the error in amplify build process while cloning repository 

Receiving objects: 100% (133/133), 949.53 KiB | 29.67 MiB/s, done.
2023-10-11T17:08:00.344Z [INFO]: # Checking for Git submodules at: /codebuild/output/src4007204090/src/PostCallAnalytics-MediaSearchFinder-1CWMR4RFQFTVI-Repo/.gitmodules
2023-10-11T17:08:00.353Z [ERROR]: !!! CustomerError: Invalid configuration file found in repository: Unexpected token < in JSON at position 610504

**Comment by accraze** [comment]
running into the same issue, would really like to use this feature

**Comment by rstrahan** [comment]
@ganapras - Thank you for both reporting and finding the fix for this issue!!  I'll commit and merge the fix.  Very much obliged to you!
