### ISSUE TITLE
Is there a way to delete specific calls?

### ISSUE THREAD

**Issue by hyde-mattholgate** [aws-samples/amazon-transcribe-post-call-analytics#211]
We are wondering if there is a method to delete specific calls that have been processed by the PCA solution and remove them from showing in the dashboard?

**Comment by chrislott** [comment]
Hi hyde-mattholgate,

Are you using the pca-dashboards CloudFormation template? If so, there isn't a great way to delete records out of the parquet datalake. You would have to craft an athena query that locates the appropriate parquet s3 path for those records, and modify the parquet to delete them.   Here's an example with CSV files in S3: https://repost.aws/knowledge-center/find-s3-source-file-athena-table-row
