### ISSUE TITLE
Cognito Permissions to look down which calls users can view

### ISSUE THREAD

**Issue by hyde-mattholgate** [aws-samples/amazon-transcribe-post-call-analytics#212]
Is there any way of using Cognito or any other method as part of the PCA solution to lock down which calls certain users can view in the dashboard?

Is there any sort of general permissions that can be applied to users?

**Comment by chrislott** [comment]
Hi hyde-mattholgate, 

Currently there is not a way to do this, however the[ List lambda function](https://github.com/aws-samples/amazon-transcribe-post-call-analytics/blob/develop/pca-ui/src/lambda/list.js) in the pca-ui could potentially filter the DynamoDB query based on the authorizer claims. Do you have any more details on how you would like the call list to be filtered? 

Chris
