### ISSUE TITLE
Bulk process more files than limit set with BulkUploadMaxTranscribeJobs 

### ISSUE THREAD

**Issue by rosmartorres** [aws-samples/amazon-transcribe-post-call-analytics#224]
We found that when we add many files to bulk bucket this files are being moving and creating more trascription job than the limit set in BulkUploadMaxTranscribeJobs paramater store. The discover was that despite we saw transcription jobs running the lambda bulk-queue-space always return 0 in the "found" variable, this is because now the jobs created by the PCA solution creates "post call analytics Jobs", and the current function doesn't return this kind of jobs in the list, to fix this we changed the code [pca-server/src/pca/pca-aws-sf-bulk-queue-space.py](https://github.com/aws-samples/amazon-transcribe-post-call-analytics/blob/develop/pca-server/src/pca/pca-aws-sf-bulk-queue-space.py) as follow:

`
    response = client.list_call_analytics_jobs(Status=status)
    found = len(response["CallAnalyticsJobSummaries"])
    while ("NextToken" in response) and (found <= filesLimit):
        response = client.list_call_analytics_jobs(Status=status, NextToken=response["NextToken"])
        found += len(response["CallAnalyticsJobSummaries"])`

**Comment by chrislott** [comment]
Hi rosmartorres, 

Thanks for submitting this issue - it makes sense that we should count both the Transcribe Call Analytics and Transcribe Standard jobs - in the code it is only taking into account standard Transcribe.  We will fix this in an upcoming release.

Chris

**Comment by chrislott** [comment]
Doing a bit more investigating -- you'll also want to update the other line as well:

`    response = client.list_transcription_jobs(Status=status)`

should become:

`    response = client.list_call_analytics_jobs(Status=status)`
