### ISSUE TITLE
Kendra Error when updating stack version

### ISSUE THREAD

**Issue by simpleverso** [aws-samples/amazon-transcribe-post-call-analytics#230]
Hello team, when updating stack we are facing the following error:

"Invalid request provided: You cannot configure Storage Capacity Units below your current consumed Storage Capacity."

after looking at Ctrail we found:
      }
        ],
        "capacityUnits": {
            "storageCapacityUnits": 0,
            "queryCapacityUnits": 0
        }
    },

If it is the first time we run the stack, we can use: 
       }
        ],
        "capacityUnits": {
            "storageCapacityUnits": 0,
            "queryCapacityUnits": 0
        }
    },

However, if Kendra is already running, we should ask for the current "storageCapacityUnits" and "queryCapacityUnits" in the CF template.

**Comment by rstrahan** [comment]
Fixed CF syntax and released https://github.com/aws-samples/amazon-transcribe-post-call-analytics/pull/250 in v0.7.10
Hopefully this resolved the issue.
