### ISSUE TITLE
Job status not getting updated correctly in the UI

### ISSUE THREAD

**Issue by metresayn** [aws-samples/amazon-transcribe-post-call-analytics#234]
Hi Team,

This is regarding the `status` column not showing the correct value when the amazon transcribe job has succeeded but there is no actual conversation in the audio file. We get the following log in CloudWatch

`ERROR	Invoke Error 	{"errorType":"TypeError","errorMessage":"Cannot read property 'SegmentEndTime' of undefined","stack":["TypeError: Cannot read property 'SegmentEndTime' of undefined","    at createRecord (/var/task/index.js:76:69)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Promise.all (index 0)","    at async Runtime.exports.handler (/var/task/index.js:270:12)"]`

PFA job status in UI.
<img width="1295" alt="Screenshot 2024-02-08 at 10 20 39 AM" src="https://github.com/aws-samples/amazon-transcribe-post-call-analytics/assets/79046332/807d9228-2b7c-4832-ad1e-341c07eb69aa">

**Comment by chrislott** [comment]
Thanks @metresayn, this has been fixed in develop branch, will be in next release!
