### ISSUE TITLE
PCAServer fails - GlueDatabase

### ISSUE THREAD

**Issue by mkoutsogcrayon** [aws-samples/amazon-transcribe-post-call-analytics#256]
PCAServer resource creation fails. The error I am getting is 

Embedded stack arn:aws:cloudformation:us-east-1:xxxxxxxxxxx:stack/PostCallAnalytics-PCAServer-1Lxxxxxxxx/xxxxxxxx-xxxx-xxxx.. was not successfully created: The following resource(s) failed to create: [GlueDatabase].

Do you have a clue what might be the issue? 
I am trying to deploy with EnablePcaDashboards --> no (no QuickSights)

**Comment by kishd** [comment]
Can you navigate to the nested stack and copy/paste the error message for the GlueDatabase resource? It should show this under the Events tab of your stack.

**Comment by rstrahan** [comment]
Closing due to lack of follow-up.  Please reopen if issue remains.
