### ISSUE TITLE
Cloud Formation Failure on SSM module

### ISSUE THREAD

**Issue by knightfoxapps** [aws-samples/amazon-transcribe-post-call-analytics#257]
I keep getting this error when running the CloudFormation:

Embedded stack arn:aws:cloudformation:us-east-1:679819004921:stack/PostCallAnalytics-version2-SSM-14XZ7KY58ACHE/7e0cfda0-07cf-11ef-b9bd-0affc2bcb0d7 was not successfully created: The following resource(s) failed to create: [TranscribeApiModeParameter, TelephonyCTRFileSuffixParameter, FilenameGUIDRegexParameter, SupportFilesBucketNameParameter, EntityRecognizerEndpointParameter, FilenameDatetimeFieldMapParameter, TranscribeLanguagesParameter, BulkUploadBucketParameter, MaxSpeakersParameter, ConversationLocationParameter, DatabaseNameParameter, MinSentimentNegativeParameter, VocabFilterNameParameter, InputBucketRawAudioParameter, ContentRedactionLanguagesParameter, SpeakerSeparationTypeParameter, CustomLangModelNameParameter, OutputBucketParsedResultsParameter, ComprehendLanguagesParameter, BulkUploadStepFunctionNameParameter, OutputBucketNameParameter, InputBucketFailedTranscriptionsParameter, InputBucketNameParameter, EntityTypesParameter, VocabFilterModeParameter, StepFunctionNameParameter, InputBucketOrigTranscriptsParameter, CallRedactionTranscriptParameter, FilenameDatetimeRegexParameter, TelephonyCTRTypeParameter, VocabularyNameParameter, FilenameAgentRegexParameter, MinSentimentPositiveParameter, EntityThresholdParameter, BulkUploadMaxTranscribeJobsParameter, BulkUploadMaxDripRateParameter, InputBucketAudioPlaybackParameter, OutputBucketTranscribeResultsParameter, CallRedactionAudioParameter, FilenameCustRegexParameter, KendraIndexIdParameter, SpeakerNamesParameter, EntityStringMapParameter].

**Comment by kishd** [comment]
Hello Egbert, 
I'd recommend looking through the stack (including nested stacks) to identify a particular resource that FAILED. The rest of them would have failed because the first failed resource triggered a rollback and the resource creation for other resources got canceled. If you can pinpoint that first resource that failed and share the error, we would be able to provide better guidance.

**Comment by knightfoxapps** [comment]
my main issue now is this one:
2024-05-01 11:06:16 UTC-0500	SupportFilesBucket	
CREATE_FAILED
-	Resource handler returned message: "You have attempted to create more buckets than allowed (Service: S3, Status Code: 400, Request ID: DVY0WBWY9WZMYNE4, Extended Request ID: uts7NtLuGAMQq6fPgR22Q89KKR1ZV+FO7mud8ZypDBGZl+XtEJBWNWMv3iWAGLo7WMnsnRC39pMsWNUupPMbGmd7TI2mhS8KX88Md3UB5ss=)" (RequestToken: e6617ce5-66b4-9cf1-3085-8fd9a9308714, HandlerErrorCode: GeneralServiceException)

**Comment by kishd** [comment]
You have more than the allowed number of S3 buckets in your account. I would suggest either removing the unused buckets or request a quota increase. You can find the instructions here: https://docs.aws.amazon.com/servicequotas/latest/userguide/request-quota-increase.html

**Comment by knightfoxapps** [comment]
i solved my S3 issue but I am back at square 1 with the same issue i reported up top. It fails with the SSM. 
![Screenshot 2024-05-01 at 8 38 16 PM](https://github.com/aws-samples/amazon-transcribe-post-call-analytics/assets/7284822/7ad9865d-4d77-4463-adfe-9e7141f419ec)

**Comment by kishd** [comment]
You will have to navigate to the nested stack PostCallAnalytics-version2-SSM-XXXXXX and identify the resource that failed to create (The first failure event under the Events tab). Note that the events are shows most recent first so you need to navigate down to find the first occurrence of the CREATE_FAILED event. I suspect you already have an existing deployment of PCA or one that didn't completely rollback. If that is the case, I would first clean up the older stack and retry.

**Comment by knightfoxapps** [comment]
im not getting an issue in any of the nested tasks that are running. they complete but then the main one creates this SSM error and fails. What is the SSM stack which gets created after the LLM Prompt is completed. The other one I see fail is the Bedrock Boto3 Layer.

**Comment by kishd** [comment]
The stacks may have rolled back and deleted. Choose the "Deleted" dropdown under stacks and look through the nested stacks (SSM and perhaps the Boto3 Layer first, then the rest of the nested stacks). 

You have to find the CREATE_FAILED event that triggered the stack to rollback and provide the failure reason to be able to further troubleshoot the issue.

**Comment by rstrahan** [comment]
Thread has gone quiet.. Closing for now, but please reopen if issue remains.
