### ISSUE TITLE
Newer Anthropic Models

### ISSUE THREAD

**Issue by BlakeItOut** [aws-samples/amazon-transcribe-post-call-analytics#259]
With the release of the newer Anthropic models there are significant improvements across the board but they do have different contracts to interact with them. Adding newer Anthropic models like Haiku, Sonnet, and Opus to be used for summarization and query would likely be worth the lift to account for these different contracts particularly Haiku.

**Comment by chrislott** [comment]
Related to #260 260

**Comment by chrislott** [comment]
@BlakeItOut Any chance you can merge and test #260 ?

**Comment by rstrahan** [comment]
v0.7.9 (2024-05-24) added support for Anthropic Claude Haiku and Sonnet models to perform call summarization and queries.
