### ISSUE TITLE
Error when deploying template, unable to create codecommit repository

### ISSUE THREAD

**Issue by lanfig** [aws-samples/amazon-transcribe-post-call-analytics#265]
I tried to deploy the solution and the template is failing. Error message says it cannot create a codecommit repository. Diving deeper it is failing because codecommit has been deprecated since july 25:https://aws.amazon.com/blogs/devops/how-to-migrate-your-aws-codecommit-repository-to-another-git-provider/
So thats why the template fails because is not able to create a new codecommit repository. Only accounts with an existing codecommit repository would be able to use the template. Any workaround? Thanks!

**Comment by rstrahan** [comment]
Thanks - will be fixed in next release

**Comment by rstrahan** [comment]
Fixed in 0.7.10
