### ISSUE TITLE
Replication of PCA with EKS endpoints

### ISSUE THREAD

**Issue by akashlp27** [aws-samples/amazon-transcribe-post-call-analytics#266]
Thank you for the detailed architectural overview for setting up post-call analytics (PCA). 
If I were to use my own AI models deployed in EKS with a Horizontal Pod Autoscaler (HPA), what adjustments would be necessary to efficiently manage scalable PCA?

**Comment by rstrahan** [comment]
Hi @akashlp27 Use a custom Lambda function to have PCA use any AI model, hosted on EKS or any other way you like - see https://github.com/aws-samples/amazon-transcribe-post-call-analytics?tab=readme-ov-file#summary-deployment-instructions
